proyectois/urls.py
from django.contrib import admin
from django.urls import path, include

from seguridadApp.views.views import acceder, home, salir, perfil
from ventasApp.views.views import dashboard

from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Api docs",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.minenick.pe",
        contact=openapi.Contact(email="nvegas@unitru.edu.pe"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
)

urlpatterns = [
    path('', acceder, name='login'),
    path('home/', home, name='home'),
    path('logout/', salir, name="logout"),

    path('perfil/', perfil, name="perfil"),
    path('usuario/', include('seguridadApp.routes.usuario'), name="usuario"),
    path('permiso/', include('seguridadApp.routes.permiso'), name="permiso"),
    path('role/', include('seguridadApp.routes.role'), name="role"),

    path('admin/', admin.site.urls, name="admin"),

    path('categoria/', include('ventasApp.routes.categoria'), name="categoria"),
    path('cliente/', include('ventasApp.routes.cliente'), name="cliente"),
    path('formaPago/', include('ventasApp.routes.formaPago'), name="formaPago"),
    path('producto/', include('ventasApp.routes.producto'), name="producto"),
    path('proveedor/', include('ventasApp.routes.proveedor'), name="proveedor"),
    path('tipoCliente/', include('ventasApp.routes.tipoCliente'), name="tipoCliente"),
    path('trabajador/', include('ventasApp.routes.trabajador'), name="trabajador"),
    path('pedidoVenta/', include('ventasApp.routes.pedidoVenta'), name="pedidoVenta"),
    path('ordenCompra/', include('ventasApp.routes.ordenCompra'), name="ordenCompra"),
    path('notaAlmacen/', include('ventasApp.routes.notaAlmacen'), name="notaAlmacen"),

    path('dashboard/', dashboard, name="dashboard"),
    path('api/', include('ventasApp.routes.api'), name="api"),
    path('api/', include('api.api.urls'), name="api2"),
    path('docs/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
]

ventasApp/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
# User model ya creado.
#=== VISTAS ESTRUCTURA (VALOR - LO Q SE MUESTRA) ====

#========= VISTA SEXO =========
MASCULINO = 'M'
FEMENINO = 'F'
SEXO = (
        (MASCULINO, 'Masculino'),
        (FEMENINO, 'Femenino'),
    )
#========= FIN SEXO =============

# Tabla de "Trabajador"
class Trabajador(models.Model):
    idTrabajador = models.AutoField(primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=100)
    direccion = models.CharField(max_length=150,blank=True, null=True)
    email = models.EmailField()
    telefono = models.CharField(max_length=9,blank=True, null=True)    
    sexo = models.CharField(max_length=1, choices=SEXO, default=MASCULINO)
    activo = models.BooleanField(default= True)
    eliminado = models.BooleanField(default= False)
    usuarioRegistro = models.CharField(max_length=300,default='admin')
    fechaRegistro = models.DateField(default= datetime.datetime.now())
    usuarioModificacion = models.CharField(max_length=300,blank=True, null=True)
    fechaModificacion = models.DateField(blank=True, null=True)
    usuarioEliminacion = models.CharField(max_length=300,blank=True, null=True)
    fechaEliminacion = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.nombres

#Borrar 
class TipoCliente(models.Model):
    idTipoCliente = models.AutoField(primary_key=True)

    descripcion = models.CharField(max_length=50)
    
    activo = models.BooleanField(default= True)
    eliminado = models.BooleanField(default= False)

    usuarioRegistro = models.CharField(max_length=300,default='admin')
    fechaRegistro = models.DateField(default= datetime.datetime.now())
    usuarioModificacion = models.CharField(max_length=300,blank=True, null=True)
    fechaModificacion = models.DateField(blank=True, null=True)
    usuarioEliminacion = models.CharField(max_length=300,blank=True, null=True)
    fechaEliminacion = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.descripcion

#========= VISTA TIPO DOCUMENTO =========
DNI = 'DNI'
RUC = 'RUC'
PASAPORTE = 'PASAPORTE'
OTRO = 'OTRO'
TIPODOCUMENTOIDENTIDAD  = (     
        (DNI, 'Documento Nacional de Identidad'),
        (RUC, 'Registro Único de Contribuyentes'),
        (PASAPORTE, 'Pasaporte'),
        (OTRO, 'Otro'),
    )
#========= FIN TIPO DOCUMENTO =============

# Tabla de "Cliente"
class Cliente(models.Model):
    idCliente = models.AutoField(primary_key=True)
    tipoCliente = models.ForeignKey(TipoCliente, on_delete = models.CASCADE)

    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=100)
    direccion = models.CharField(max_length=150)
    email = models.EmailField()
    telefono = models.CharField(max_length=9)
    user = models.CharField(max_length = 120,default = "")
    password = models.CharField(max_length = 120, default = "")
    tipoDocumentoIdentidad = models.CharField(max_length=50, choices= TIPODOCUMENTOIDENTIDAD, default= DNI)
    documentoIdentidad = models.CharField(max_length=50)

    activo = models.BooleanField(default= True)
    eliminado = models.BooleanField(default= False)
        
    usuarioRegistro = models.CharField(max_length=300,default='admin')
    fechaRegistro = models.DateField(default= datetime.datetime.now())
    usuarioModificacion = models.CharField(max_length=300,blank=True, null=True)
    fechaModificacion = models.DateField(blank=True, null=True)
    usuarioEliminacion = models.CharField(max_length=300,blank=True, null=True)
    fechaEliminacion = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.nombres

#========= VISTA FRECUENCIA =========
BIMENSUAL = 'BIMENSUAL'
TRIMESTRAL = 'TRIMESTRAL'
ANUAL = 'ANUAL'
FRECUENCIA = (
        (BIMENSUAL,'Bimensual'),
        (TRIMESTRAL,'Trimestral'),
        (ANUAL ,'Anual'),
    )
#========= FIN FRECUENCIA =============

#Borrar
class FormaPago(models.Model):
    idFormaPago = models.AutoField(primary_key=True)
    
    descripcion = models.CharField(max_length=100)
    nroCuotas = models.IntegerField()
    frecuencia = models.CharField(max_length=50,choices=FRECUENCIA, default=BIMENSUAL)
    interes = models.FloatField()

    activo = models.BooleanField(default= True)
    eliminado = models.BooleanField(default= False)
    usuarioRegistro = models.CharField(max_length=300,default='admin')
    fechaRegistro = models.DateField(default= datetime.datetime.now())
    usuarioModificacion = models.CharField(max_length=300,blank=True, null=True)
    fechaModificacion = models.DateField(blank=True, null=True)
    usuarioEliminacion = models.CharField(max_length=300,blank=True, null=True)
    fechaEliminacion = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.descripcion

# Tabla de "Categoria"
class Categoria(models.Model):
    idCategoria=models.AutoField(primary_key=True)
    descripcion=models.CharField(max_length=100)
    activo = models.BooleanField(default= True)
    eliminado = models.BooleanField(default= False)
    usuarioRegistro = models.CharField(max_length=300,default='admin')
    fechaRegistro = models.DateField(default= datetime.datetime.now())
    usuarioModificacion = models.CharField(max_length=300,blank=True, null=True)
    fechaModificacion = models.DateField(blank=True, null=True)
    usuarioEliminacion = models.CharField(max_length=300,blank=True, null=True)
    fechaEliminacion = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.descripcion

# Tabla de "Producto"
class Producto(models.Model):
    idProducto = models.AutoField(primary_key=True)
    categoria=models.ForeignKey(Categoria, on_delete=models.CASCADE)
    codigo = models.CharField(max_length=10)

    nombre = models.CharField(max_length=100)
    descripcion = models.CharField(max_length=100)
    marca = models.CharField(max_length=100)
    modelo = models.CharField(max_length=100)
    stock = models.IntegerField()

    precioUnitario = models.FloatField()

    urlImagen = models.CharField(max_length=1000,blank=True, null=True)
    nombreImagen = models.CharField(max_length=1000,blank=True, null=True)
    fechaCargaImagen = models.DateField(blank=True, null=True)

    activo = models.BooleanField(default= True)
    eliminado = models.BooleanField(default= False)
    usuarioRegistro = models.CharField(max_length=300,default='admin')
    fechaRegistro = models.DateField(default= datetime.datetime.now())
    usuarioModificacion = models.CharField(max_length=300,blank=True, null=True)
    fechaModificacion = models.DateField(blank=True, null=True)
    usuarioEliminacion = models.CharField(max_length=300,blank=True, null=True)
    fechaEliminacion = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.idProducto

#========= VISTA TIPOMONEDA =========
SOLES = 'SOLES'
DOLARES = 'DOLARES'
EUROS = 'EUROS'
TIPOMONEDA  = (
    (SOLES ,'Soles'),
    (DOLARES ,'Dolares'),
    (EUROS ,'Euros'),
)
#========= FIN TIPOMONEDA  =============
#========= VISTA ESTADO =========
ABIERTA = 1
CERRADA = 2
LIBERADA = 3
ANULADA = 4
ESTADO  = (
    (ABIERTA ,'Abierta'),
    (CERRADA ,'Cerrada'),
    (ANULADA ,'Anulada'),
)
#========= FIN ESTADO  =============

#========= VISTA TIPODOCUMENTO =========
BOLETA = 'BOLETA'
FACTURA = 'FACTURA'
TIPODOCUMENTO  = (
    (BOLETA ,'Boleta'),
    (FACTURA ,'Factura'),
)
#========= FIN TIPODOCUMENTO  =============


# Tabla de "Pedido de Venta"
class PedidoVenta(models.Model):
    idPedidoVenta = models.AutoField(primary_key=True)
    trabajador = models.ForeignKey(Trabajador, on_delete = models.CASCADE)
    cliente = models.ForeignKey(Cliente, on_delete = models.CASCADE)
    formaPago = models.ForeignKey(FormaPago, on_delete = models.CASCADE)
    codigo = models.CharField(max_length=10)
    fechaEmision = models.DateField()
    fechaEntrega = models.DateField()
    tipoDocumento = models.CharField(max_length=20,choices=TIPODOCUMENTO, default=BOLETA)
    tipoMoneda= models.CharField(max_length=50,choices=TIPOMONEDA, default=SOLES)
    tasaCambio = models.FloatField()
    subtotal = models.FloatField()

    tasaIgv = models.FloatField()
    descuento = models.FloatField()
    
    total = models.FloatField() 

    estado = models.IntegerField(choices=ESTADO, default=ABIERTA)

    eliminado = models.BooleanField(default= False)
    usuarioRegistro = models.CharField(max_length=300,default='admin')
    fechaRegistro = models.DateField(default= datetime.datetime.now())
    usuarioModificacion = models.CharField(max_length=300,blank=True, null=True)
    fechaModificacion = models.DateField(blank=True, null=True)
    usuarioEliminacion = models.CharField(max_length=300,blank=True, null=True)
    fechaEliminacion = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.codigo

# Tabla de "Detalle Pedido de Venta"
class DetallePedidoVenta(models.Model):
    idDetallePedidoVenta = models.AutoField(primary_key=True)
    pedidoVenta = models.ForeignKey(PedidoVenta, on_delete = models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete = models.CASCADE)
    cantidad = models.IntegerField()
    precioUnitario = models.FloatField()
    descuentoUnitario = models.FloatField()
    precio = models.FloatField()

    eliminado = models.BooleanField(default= False)
    usuarioRegistro = models.CharField(max_length=300,default='admin')
    fechaRegistro = models.DateField(default= datetime.datetime.now())
    usuarioModificacion = models.CharField(max_length=300,blank=True, null=True)
    fechaModificacion = models.DateField(blank=True, null=True)
    usuarioEliminacion = models.CharField(max_length=300,blank=True, null=True)
    fechaEliminacion = models.DateField(blank=True, null=True)

    def __str__(self):

ventasApp/routes/api.py
from django.urls import path
from ventasApp.views.api import *

urlpatterns = [
    path('get_countCompras/',get_countCompras ,name="get_countCompras"),
    path('get_countVentas/',get_countVentas ,name="get_countVentas"),
    path('get_dataDona/',get_dataDona,name="get_dataDona"), 
    path('get_dataLine/',get_dataLine,name="get_dataLine"),
    path('get_top_clients_chart/',get_top_clients_chart,name="get_top_clients_chart"), 
    
    path('get_detallePedidoVenta/<int:id>/',obtenerDetallePedidoVenta,name="detallepedidoVenta"),
    path('get_detalleOrdenCompra/<int:id>/',obtenerDetalleOrdenCompra,name="detalleordenCompra"),
    path('get_detalleNotaAlmacen/<int:id>/',obtenerDetalleNotaAlmacen,name="detallenotaAlmacen"),
    path('get_tipoNotaAlmacen/<int:id>/',obtenerTipoNotaAlmacen,name="tipoNotaAlmacen"),
    
    path('get_cliente/<int:id>/',obtenerCliente,name="obtenerCliente"),
    path('get_proveedor/<int:id>/',obtenerProveedor,name="obtenerProveedor"),
]

ventasApp/routes/categoria.py
from django.urls import path
from ventasApp.views import categoria

urlpatterns = [
    path('',categoria.listarcategoria,name="listarcategoria"),
    path('create/',categoria.agregarcategoria ,name="agregarcategoria"),
    path('edit/<int:id>/',categoria.editarcategoria ,name="editarcategoria"),
    path('delete/<int:id>/',categoria.eliminarcategoria,name="eliminarcategoria"), 
    path('active/<int:id>/<int:activo>/',categoria.activarcategoria,name="activarcategoria"), 
]

ventasApp/routes/cliente.py
from django.urls import path
from ventasApp.views import cliente

urlpatterns = [
    path('',cliente.listarcliente,name="listarcliente"),
    path('create/',cliente.agregarcliente ,name="agregarcliente"),
    path('edit/<int:id>/',cliente.editarcliente ,name="editarcliente"),
    path('delete/<int:id>/',cliente.eliminarcliente,name="eliminarcliente"), 
    path('active/<int:id>/<int:activo>/',cliente.activarcliente,name="activarcliente"), 
]

ventasApp/routes/formaPago.py
from django.urls import path
from ventasApp.views import formaPago

urlpatterns = [
    path('',formaPago.listarformaPago,name="listarformaPago"),
    path('create/',formaPago.agregarformaPago ,name="agregarformaPago"),
    path('edit/<int:id>/',formaPago.editarformaPago ,name="editarformaPago"),
    path('delete/<int:id>/',formaPago.eliminarformaPago,name="eliminarformaPago"), 
    path('active/<int:id>/<int:activo>/',formaPago.activarformaPago,name="activarformaPago"), 
]

ventasApp/routes/notaAlmacen.py
from django.urls import path
from ventasApp.views import notaAlmacen

urlpatterns = [
    path('',notaAlmacen.listarnotaAlmacen,name="listarnotaAlmacen"),
    path('create/',notaAlmacen.agregarnotaAlmacen ,name="agregarnotaAlmacen"),
    path('edit/<int:id>/',notaAlmacen.editarnotaAlmacen ,name="editarnotaAlmacen"),
    path('delete/<int:id>/',notaAlmacen.eliminarnotaAlmacen,name="eliminarnotaAlmacen"), 
    path('active/<int:id>/<int:activo>/',notaAlmacen.activarnotaAlmacen,name="activarnotaAlmacen"),
]

ventasApp/routes/ordenCompra.py
from django.urls import path
from ventasApp.views.ordenCompra import *

urlpatterns = [
    path('',listarordenCompra,name="listarordenCompra"),
    path('create/',agregarordenCompra ,name="agregarordenCompra"),
    path('edit/<int:id>/',editarordenCompra ,name="editarordenCompra"),
    path('delete/<int:id>/',eliminarordenCompra,name="eliminarordenCompra"), 
    path('active/<int:id>/<int:activo>/',activarordenCompra,name="activarordenCompra"),
     path('pdf/<int:id>',ListOrdenCompraPdf,name='pdfOrdenCompra'),
]

ventasApp/routes/pedidoVenta.py
from django.urls import path
from ventasApp.views.pedidoVenta import *

urlpatterns = [
    path('',listarpedidoVenta,name="listarpedidoVenta"),
    path('create/',agregarpedidoVenta,name="agregarpedidoVenta"),
    path('edit/<int:id>/',editarpedidoVenta,name="editarpedidoVenta"),
    path('delete/<int:id>/',eliminarpedidoVenta,name="eliminarpedidoVenta"), 
    path('pdf/<int:id>',ListPedidoVentaPdf,name='pdfpedidoVenta'),
]

ventasApp/routes/producto.py
from django.urls import path
from ventasApp.views import producto

urlpatterns = [
    path('',producto.listarproducto,name="listarproducto"),
    path('create/',producto.agregarproducto ,name="agregarproducto"),
    path('edit/<int:id>/',producto.editarproducto ,name="editarproducto"),
    path('delete/<int:id>/',producto.eliminarproducto,name="eliminarproducto"), 
    path('active/<int:id>/<int:activo>/',producto.activarproducto,name="activarproducto"), 
]

ventasApp/routes/proveedor.py
from django.urls import path
from ventasApp.views import proveedor

urlpatterns = [
    path('',proveedor.listarproveedor,name="listarproveedor"),
    path('create/',proveedor.agregarproveedor ,name="agregarproveedor"),
    path('edit/<int:id>/',proveedor.editarproveedor ,name="editarproveedor"),
    path('delete/<int:id>/',proveedor.eliminarproveedor,name="eliminarproveedor"), 
    path('active/<int:id>/<int:activo>/',proveedor.activarproveedor,name="activarproveedor"), 
]

ventasApp/routes/tipoCliente.py
from django.urls import path
from ventasApp.views import tipoCliente

urlpatterns = [
    path('',tipoCliente.listartipoCliente,name="listartipoCliente"),
    path('create/',tipoCliente.agregartipoCliente ,name="agregartipoCliente"),
    path('edit/<int:id>/',tipoCliente.editartipoCliente ,name="editartipoCliente"),
    path('delete/<int:id>/',tipoCliente.eliminartipoCliente,name="eliminartipoCliente"), 
    path('active/<int:id>/<int:activo>/',tipoCliente.activartipoCliente,name="activartipoCliente"), 
]

ventasApp/templates/cliente/agregar.html
{% extends "plantilla.html" %}
{% block title %} Minimarket  | Categoria {% endblock title %}

{% block content %}
{% load crispy_forms_tags %}
<div class="p-3">
    <div class="card card-info mx-4 my-4">
        <div class="card-header" style="background-color:#fff;">
            <h1 class="card-title" style="color: #000; font-weight: 600; margin: 15px 50px;">AGREGAR CLIENTE</h1>
        </div>
        
        <div class="card-body"style="margin: 20px 50px;">

            
            <form method="post">
            {% csrf_token %}
            <div class="row">                
                <div class="col-12 col-lg-6">
                   {{ form.tipoCliente|as_crispy_field }}                                         
                </div>                 
                <div class="col-12 col-lg-6">
                    
                </div> 
                <div class="col-12 col-lg-6">
                    {{ form.apellidos|as_crispy_field }}
                </div>
                <div class="col-12 col-lg-6">
                    {{ form.nombres|as_crispy_field }}
                </div>
                <div class="col-12 col-lg-7">
                    {{ form.direccion|as_crispy_field }}
                </div>
                <div class="col-12 col-lg-5">
                    {{ form.email|as_crispy_field }}
                </div>
                <div class="col-12 col-lg-4">
                    {{ form.telefono|as_crispy_field }}
                </div>
                <div class="col-12 col-lg-4">
                    {{ form.tipoDocumentoIdentidad|as_crispy_field }}                    
                </div>
                <div class="col-12 col-lg-4">
                    {{ form.documentoIdentidad|as_crispy_field }}
                </div>
                <div class="col-12 col-lg-12">
                    {{ form.activo|as_crispy_field }}
                </div>
            </div>

            <div class="d-flex justify-content-end">
                <a href="{% url 'listarcliente' %}" class="btn btn-secondary">Cancelar</a> &nbsp;
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
            </form>
        </div>
        
    </div>
</div>
</div>
{% endblock%} 

{% block js %}
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% if messages %}
        {% for m in messages %}
            <script>
                Swal.fire({
                "title": "Warning",
                "text":"{{m}}",
                "icon":"info"
                })
            </script>
        {% endfor %}
    {% endif %}
{% endblock%} 

ventasApp/templates/cliente/listar.html
{% extends "plantilla.html" %}
{% block title %} Minimarket  | Cliente {% endblock title %}

{% block content %}
    <div class="p-3">
        <div class="card mt-3">
        <div class="card-header d-flex justify-content-between p-3">
            <div>
                <h1 class="card-title align-items-center" style="font-weight: 700;  margin: 5px 30px;">LISTADO DE CLIENTES</h1>
            </div>
            {% if perms.ventasApp.add_cliente %}
            <div class="ml-auto" style="margin-right: 30px;">
                <a href="{% url 'agregarcliente' %}" class='btn btn-sm btn-primary'>
                    <i class='fas fa-plus'></i> NUEVO
                </a>
            </div>
            {% endif %}
        </div>
        <div class="card-body"  style="margin: 5px 40px;">
            <div class="row">
                <div class="col-12 col-md-4">
                    <form action="" method="GET">
                        <div class="input-group">
                            <input type="text" name="buscar" id="buscar" class="form-control" autofocus placeholder="Buscar dni" value=""><span class="input-group-btn">
                            <button class="btn btn-primary"><i class="fa fa-search"></i></button></span>
                        </div>
                    </form>
                </div>
            </div>
            <br>
            <table class="table" style="width:100%">
                <thead class="table-dark">
                    <tr>
                        <th>Id</th>
                        <th>Tipo Cliente</th>                        
                        <th>Tipo Documento</th>
                        <th>Documento</th>
                        <th>Apellidos y Nombres</th>
                        <th>Direccion</th>
                        <th>Email</th>
                        {% if perms.ventasApp.change_cliente and perms.ventasApp.delete_cliente %}
                        <th>Activo</th>
                        <th><center>Opciones</center></th>
                        {% endif %}
                    </tr>
                </thead>
                {% if page_obj %}
                {% for itemcliente in page_obj %}
                <tr>
                    <td>{{ itemcliente.idCliente}}</td>
                    <td>{{ itemcliente.tipoCliente}}</td>
                    <td><center>{{ itemcliente.tipoDocumentoIdentidad }}</center></td>
                    <td>{{ itemcliente.documentoIdentidad }}</td>
                    <td>{{ itemcliente.apellidos }} {{ itemcliente.nombres }}</td>
                    <td>{{ itemcliente.direccion }}</td>
                    <td>{{ itemcliente.email }}</td>                    
                    {% if perms.ventasApp.change_cliente and perms.ventasApp.delete_cliente %}
                    <td>
                        <label class="switch">
                            <input type="checkbox" onclick="activarCliente('{{itemcliente.idCliente}}','{{itemcliente.activo}}')" {% if itemcliente.activo %} checked {% endif %} >
                            <span class="slider round"></span>
                        </label>
                    </td>
                    <td style="text-align: center;">
                        <a href="{% url 'editarcliente' itemcliente.idCliente %}" class="btn btn-success btn-sm"><i class="fa fa-edit"></i></a>
                        <a href="#" onclick="eliminarCliente('{{itemcliente.idCliente}}','{{itemcliente.descripcion}}')" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>
                    </td>
                    {% endif %}
                </tr>
                {% endfor %}
                {% else %}
                <tr style="text-align: center;">
                    <td colspan="9">
                        <p>No hay Registros</p>
                    </td>
                </tr>
                {% endif %}
            </table>
            {% comment %} <nav aria-label="pagination-django">
                <ul class="pagination">
                  <li class="page-item"><a class="page-link" href="#">Previous</a></li>
                  <li class="page-item active"><a class="page-link" href="#">1</a></li>
                  <li class="page-item"><a class="page-link" href="#">2</a></li>
                  <li class="page-item"><a class="page-link" href="#">3</a></li>
                  <li class="page-item"><a class="page-link" href="#">Next</a></li>
                </ul>
            </nav> {% endcomment %}

            <div class="d-flex justify-content-end pt-2">
                <nav aria-label="pagination-django">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}                    
                            <li class="page-item"><a class="page-link" href="?page=1">First</a></li>
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}"><<</a></li>                        
                            
                        {% endif %}
                        
                        <li class="page-item"><a class="page-link">Página {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</a></li>

                        {% if page_obj.has_next %}
                        
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">>></a></li>
                            
                            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    {% if messages %}
    {% for m in messages %}
        <script>
            Swal.fire({
            "title": "Éxito",
            "text":"{{m}}",
            "icon":"success"
            })
            console.log("{{m}}")
        </script>
    {% endfor %}
    {% endif %}
    <script>
        function eliminarCliente(id,descripcion){
            Swal.fire({ "title":"¿Realmente desea eliminar Registro?",
            "text":"Código :"+ id + " - Descripción :" + descripcion,
            "icon":"question",
            "showCancelButton":true,
            "cancelButtonText":"No",
            "confirmButtonText":"Si",
            "reverseButton":true,
            "confirmButtonColor":"#dc3545"
            }).then(function(result){ if(result.isConfirmed){
                window.location.replace(window.location.origin+"/cliente/delete/"+id+"/") }
        });
        }

        function activarCliente(id,activo){
            let estado;
            if(activo=='False')
                estado=0
            else
                estado=1
                window.location.replace(window.location.origin+"/cliente/active/"+id+"/"+ estado +"/")
        };
</script>
{% endblock js %} 

{% block css %}
    <style>
    .switch {
      position: relative;
      display: inline-block;
      width: 60px;
      height: 34px;
    }
    
    .switch input { 
      opacity: 0;
      width: 0;
      height: 0;
    }
    
    .slider {
      position: absolute;
      cursor: pointer;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      background-color: #ccc;
      -webkit-transition: .4s;
      transition: .4s;
    }
    
    .slider:before {
      position: absolute;
      content: "";
      height: 26px;
      width: 26px;
      left: 4px;
      bottom: 4px;
      background-color: white;
      -webkit-transition: .4s;
      transition: .4s;
    }
    
    input:checked + .slider {
      background-color: #2196F3;
    }
    
    input:focus + .slider {
      box-shadow: 0 0 1px #2196F3;
    }
    
    input:checked + .slider:before {
      -webkit-transform: translateX(26px);
      -ms-transform: translateX(26px);
      transform: translateX(26px);
    }
    
    /* Rounded sliders */
    .slider.round {
      border-radius: 34px;
    }
    
    .slider.round:before {
      border-radius: 50%;
    }
    </style>
{% endblock css %}